gamerule sendcommandfeedback false
give @s block:camouflage_wallpaper_white
give @s block:camouflage_wallpaper_light_gray
give @s block:camouflage_wallpaper_gray
give @s block:camouflage_wallpaper_black
give @s block:camouflage_wallpaper_brown
give @s block:camouflage_wallpaper_red
give @s block:camouflage_wallpaper_orange
give @s block:camouflage_wallpaper_yellow
give @s block:camouflage_wallpaper_lime
give @s block:camouflage_wallpaper_green
give @s block:camouflage_wallpaper_cyan
give @s block:camouflage_wallpaper_light_blue
give @s block:camouflage_wallpaper_blue
give @s block:camouflage_wallpaper_purple
give @s block:camouflage_wallpaper_magenta
give @s block:camouflage_wallpaper_pink
gamerule sendcommandfeedback true