gamerule sendcommandfeedback false
give @s block:ceramic_tile_white
give @s block:ceramic_tile_light_gray
give @s block:ceramic_tile_gray
give @s block:ceramic_tile_black
give @s block:ceramic_tile_brown
give @s block:ceramic_tile_red
give @s block:ceramic_tile_orange
give @s block:ceramic_tile_yellow
give @s block:ceramic_tile_lime
give @s block:ceramic_tile_green
give @s block:ceramic_tile_cyan
give @s block:ceramic_tile_light_blue
give @s block:ceramic_tile_blue
give @s block:ceramic_tile_purple
give @s block:ceramic_tile_magenta
give @s block:ceramic_tile_pink
gamerule sendcommandfeedback true