gamerule sendcommandfeedback false
give @s block:ceramic_vinyl_white
give @s block:ceramic_vinyl_light_gray
give @s block:ceramic_vinyl_gray
give @s block:ceramic_vinyl_black
give @s block:ceramic_vinyl_brown
give @s block:ceramic_vinyl_red
give @s block:ceramic_vinyl_orange
give @s block:ceramic_vinyl_yellow
give @s block:ceramic_vinyl_lime
give @s block:ceramic_vinyl_green
give @s block:ceramic_vinyl_cyan
give @s block:ceramic_vinyl_light_blue
give @s block:ceramic_vinyl_blue
give @s block:ceramic_vinyl_purple
give @s block:ceramic_vinyl_magenta
give @s block:ceramic_vinyl_pink
gamerule sendcommandfeedback true