gamerule sendcommandfeedback false
give @s block:chair_white
give @s block:chair_light_gray
give @s block:chair_gray
give @s block:chair_black
give @s block:chair_brown
give @s block:chair_red
give @s block:chair_orange
give @s block:chair_yellow
give @s block:chair_lime
give @s block:chair_green
give @s block:chair_cyan
give @s block:chair_light_blue
give @s block:chair_blue
give @s block:chair_purple
give @s block:chair_magenta
give @s block:chair_pink
gamerule sendcommandfeedback true