gamerule sendcommandfeedback false
give @s block:checkered_tile_white
give @s block:checkered_tile_light_gray
give @s block:checkered_tile_gray
give @s block:checkered_tile_black
give @s block:checkered_tile_brown
give @s block:checkered_tile_red
give @s block:checkered_tile_orange
give @s block:checkered_tile_yellow
give @s block:checkered_tile_lime
give @s block:checkered_tile_green
give @s block:checkered_tile_cyan
give @s block:checkered_tile_light_blue
give @s block:checkered_tile_blue
give @s block:checkered_tile_purple
give @s block:checkered_tile_magenta
give @s block:checkered_tile_pink
gamerule sendcommandfeedback true