gamerule sendcommandfeedback false
give @s block:chevron_wallpaper_white
give @s block:chevron_wallpaper_light_gray
give @s block:chevron_wallpaper_gray
give @s block:chevron_wallpaper_black
give @s block:chevron_wallpaper_brown
give @s block:chevron_wallpaper_red
give @s block:chevron_wallpaper_orange
give @s block:chevron_wallpaper_yellow
give @s block:chevron_wallpaper_lime
give @s block:chevron_wallpaper_green
give @s block:chevron_wallpaper_cyan
give @s block:chevron_wallpaper_light_blue
give @s block:chevron_wallpaper_blue
give @s block:chevron_wallpaper_purple
give @s block:chevron_wallpaper_magenta
give @s block:chevron_wallpaper_pink
gamerule sendcommandfeedback true