gamerule sendcommandfeedback false
give @s block:chair_white
give @s block:table_white
give @s block:wall_clock_white
give @s block:picture_frame
give @s block:wall_picture_frame
give @s block:block_light_white
give @s block:incandescent_light
give @s block:fluorescent_light
give @s block:gate_light
give @s block:lamp_shade
give @s block:modern_lamp
give @s block:stone_path
give @s block:fridge
give @s block:cooking_range
give @s block:gas_stove
give @s block:microwave_oven
give @s block:kitchen_chimney
give @s item:traffic_cone
give @s block:trashcan
give @s block:steel_rod
give @s block:lpg_tank
give @s block:water_dispenser
give @s block:water_container
give @s block:countertop_block
give @s block:countertop_cabinet
give @s block:countertop_drawer
give @s block:countertop_sink
give @s block:countertop_sink_cabinet
give @s block:countertop_sink_drawer
gamerule sendcommandfeedback true