gamerule sendcommandfeedback false
give @s block:gingham_wallpaper_white
give @s block:gingham_wallpaper_light_gray
give @s block:gingham_wallpaper_gray
give @s block:gingham_wallpaper_black
give @s block:gingham_wallpaper_brown
give @s block:gingham_wallpaper_red
give @s block:gingham_wallpaper_orange
give @s block:gingham_wallpaper_yellow
give @s block:gingham_wallpaper_lime
give @s block:gingham_wallpaper_green
give @s block:gingham_wallpaper_cyan
give @s block:gingham_wallpaper_light_blue
give @s block:gingham_wallpaper_blue
give @s block:gingham_wallpaper_purple
give @s block:gingham_wallpaper_magenta
give @s block:gingham_wallpaper_pink
gamerule sendcommandfeedback true