gamerule sendcommandfeedback false
give @s block:marble_vinyl_white
give @s block:marble_vinyl_light_gray
give @s block:marble_vinyl_gray
give @s block:marble_vinyl_black
give @s block:marble_vinyl_brown
give @s block:marble_vinyl_red
give @s block:marble_vinyl_orange
give @s block:marble_vinyl_yellow
give @s block:marble_vinyl_lime
give @s block:marble_vinyl_green
give @s block:marble_vinyl_cyan
give @s block:marble_vinyl_light_blue
give @s block:marble_vinyl_blue
give @s block:marble_vinyl_purple
give @s block:marble_vinyl_magenta
give @s block:marble_vinyl_pink
gamerule sendcommandfeedback true