gamerule sendcommandfeedback false
give @s block:marble_tile_white
give @s block:marble_tile_light_gray
give @s block:marble_tile_gray
give @s block:marble_tile_black
give @s block:marble_tile_brown
give @s block:marble_tile_red
give @s block:marble_tile_orange
give @s block:marble_tile_yellow
give @s block:marble_tile_lime
give @s block:marble_tile_green
give @s block:marble_tile_cyan
give @s block:marble_tile_light_blue
give @s block:marble_tile_blue
give @s block:marble_tile_purple
give @s block:marble_tile_magenta
give @s block:marble_tile_pink
gamerule sendcommandfeedback true