gamerule sendcommandfeedback false
give @s block:modern_bookshelf_white
give @s block:modern_bookshelf_light_gray
give @s block:modern_bookshelf_gray
give @s block:modern_bookshelf_black
give @s block:modern_bookshelf_brown
give @s block:modern_bookshelf_red
give @s block:modern_bookshelf_orange
give @s block:modern_bookshelf_yellow
give @s block:modern_bookshelf_lime
give @s block:modern_bookshelf_green
give @s block:modern_bookshelf_cyan
give @s block:modern_bookshelf_light_blue
give @s block:modern_bookshelf_blue
give @s block:modern_bookshelf_purple
give @s block:modern_bookshelf_magenta
give @s block:modern_bookshelf_pink
gamerule sendcommandfeedback true