gamerule sendcommandfeedback false
give @s block:one_way_glass_white
give @s block:one_way_glass_light_gray
give @s block:one_way_glass_gray
give @s block:one_way_glass
give @s block:one_way_glass_brown
give @s block:one_way_glass_red
give @s block:one_way_glass_orange
give @s block:one_way_glass_yellow
give @s block:one_way_glass_lime
give @s block:one_way_glass_green
give @s block:one_way_glass_cyan
give @s block:one_way_glass_light_blue
give @s block:one_way_glass_blue
give @s block:one_way_glass_purple
give @s block:one_way_glass_magenta
give @s block:one_way_glass_pink
gamerule sendcommandfeedback true