gamerule sendcommandfeedback false
give @s block:plaid_wallpaper_white
give @s block:plaid_wallpaper_light_gray
give @s block:plaid_wallpaper_gray
give @s block:plaid_wallpaper_black
give @s block:plaid_wallpaper_brown
give @s block:plaid_wallpaper_red
give @s block:plaid_wallpaper_orange
give @s block:plaid_wallpaper_yellow
give @s block:plaid_wallpaper_lime
give @s block:plaid_wallpaper_green
give @s block:plaid_wallpaper_cyan
give @s block:plaid_wallpaper_light_blue
give @s block:plaid_wallpaper_blue
give @s block:plaid_wallpaper_purple
give @s block:plaid_wallpaper_magenta
give @s block:plaid_wallpaper_pink
gamerule sendcommandfeedback true