gamerule sendcommandfeedback false
give @s block:drawer_white
give @s block:drawer_light_gray
give @s block:drawer_gray
give @s block:drawer_black
give @s block:drawer_brown
give @s block:drawer_red
give @s block:drawer_orange
give @s block:drawer_yellow
give @s block:drawer_lime
give @s block:drawer_green
give @s block:drawer_cyan
give @s block:drawer_light_blue
give @s block:drawer_blue
give @s block:drawer_purple
give @s block:drawer_magenta
give @s block:drawer_pink
gamerule sendcommandfeedback true