gamerule sendcommandfeedback false
give @s block:plastic_desk_white
give @s block:plastic_desk_light_gray
give @s block:plastic_desk_gray
give @s block:plastic_desk_black
give @s block:plastic_desk_brown
give @s block:plastic_desk_red
give @s block:plastic_desk_orange
give @s block:plastic_desk_yellow
give @s block:plastic_desk_lime
give @s block:plastic_desk_green
give @s block:plastic_desk_cyan
give @s block:plastic_desk_light_blue
give @s block:plastic_desk_blue
give @s block:plastic_desk_purple
give @s block:plastic_desk_magenta
give @s block:plastic_desk_pink
gamerule sendcommandfeedback true