gamerule sendcommandfeedback false
give @s block:plastic_chiseled_white
give @s block:plastic_chiseled_light_gray
give @s block:plastic_chiseled_gray
give @s block:plastic_chiseled_black
give @s block:plastic_chiseled_brown
give @s block:plastic_chiseled_red
give @s block:plastic_chiseled_orange
give @s block:plastic_chiseled_yellow
give @s block:plastic_chiseled_lime
give @s block:plastic_chiseled_green
give @s block:plastic_chiseled_cyan
give @s block:plastic_chiseled_light_blue
give @s block:plastic_chiseled_blue
give @s block:plastic_chiseled_purple
give @s block:plastic_chiseled_magenta
give @s block:plastic_chiseled_pink
gamerule sendcommandfeedback true