gamerule sendcommandfeedback false
give @s block:cabinet_white
give @s block:cabinet_light_gray
give @s block:cabinet_gray
give @s block:cabinet_black
give @s block:cabinet_brown
give @s block:cabinet_red
give @s block:cabinet_orange
give @s block:cabinet_yellow
give @s block:cabinet_lime
give @s block:cabinet_green
give @s block:cabinet_cyan
give @s block:cabinet_light_blue
give @s block:cabinet_blue
give @s block:cabinet_purple
give @s block:cabinet_magenta
give @s block:cabinet_pink
gamerule sendcommandfeedback true