gamerule sendcommandfeedback false
give @s block:plastic_brick_white
give @s block:plastic_brick_light_gray
give @s block:plastic_brick_gray
give @s block:plastic_brick_black
give @s block:plastic_brick_brown
give @s block:plastic_brick_red
give @s block:plastic_brick_orange
give @s block:plastic_brick_yellow
give @s block:plastic_brick_lime
give @s block:plastic_brick_green
give @s block:plastic_brick_cyan
give @s block:plastic_brick_light_blue
give @s block:plastic_brick_blue
give @s block:plastic_brick_purple
give @s block:plastic_brick_magenta
give @s block:plastic_brick_pink
gamerule sendcommandfeedback true