gamerule sendcommandfeedback false
give @s block:plastic_pillar_white
give @s block:plastic_pillar_light_gray
give @s block:plastic_pillar_gray
give @s block:plastic_pillar_black
give @s block:plastic_pillar_brown
give @s block:plastic_pillar_red
give @s block:plastic_pillar_orange
give @s block:plastic_pillar_yellow
give @s block:plastic_pillar_lime
give @s block:plastic_pillar_green
give @s block:plastic_pillar_cyan
give @s block:plastic_pillar_light_blue
give @s block:plastic_pillar_blue
give @s block:plastic_pillar_purple
give @s block:plastic_pillar_magenta
give @s block:plastic_pillar_pink
gamerule sendcommandfeedback true