gamerule sendcommandfeedback false
give @s block:plastic_white
give @s block:plastic_light_gray
give @s block:plastic_gray
give @s block:plastic_black
give @s block:plastic_brown
give @s block:plastic_red
give @s block:plastic_orange
give @s block:plastic_yellow
give @s block:plastic_lime
give @s block:plastic_green
give @s block:plastic_cyan
give @s block:plastic_light_blue
give @s block:plastic_blue
give @s block:plastic_purple
give @s block:plastic_magenta
give @s block:plastic_pink
gamerule sendcommandfeedback true