gamerule sendcommandfeedback false
give @s block:plastic_carved_white
give @s block:plastic_carved_light_gray
give @s block:plastic_carved_gray
give @s block:plastic_carved_black
give @s block:plastic_carved_brown
give @s block:plastic_carved_red
give @s block:plastic_carved_orange
give @s block:plastic_carved_yellow
give @s block:plastic_carved_lime
give @s block:plastic_carved_green
give @s block:plastic_carved_cyan
give @s block:plastic_carved_light_blue
give @s block:plastic_carved_blue
give @s block:plastic_carved_purple
give @s block:plastic_carved_magenta
give @s block:plastic_carved_pink
gamerule sendcommandfeedback true