gamerule sendcommandfeedback false
give @s block:plastic_bricks_white
give @s block:plastic_bricks_light_gray
give @s block:plastic_bricks_gray
give @s block:plastic_bricks_black
give @s block:plastic_bricks_brown
give @s block:plastic_bricks_red
give @s block:plastic_bricks_orange
give @s block:plastic_bricks_yellow
give @s block:plastic_bricks_lime
give @s block:plastic_bricks_green
give @s block:plastic_bricks_cyan
give @s block:plastic_bricks_light_blue
give @s block:plastic_bricks_blue
give @s block:plastic_bricks_purple
give @s block:plastic_bricks_magenta
give @s block:plastic_bricks_pink
gamerule sendcommandfeedback true