gamerule sendcommandfeedback false
give @s block:present_white
give @s block:present_light_gray
give @s block:present_gray
give @s block:present_black
give @s block:present_brown
give @s block:present_red
give @s block:present_orange
give @s block:present_yellow
give @s block:present_lime
give @s block:present_green
give @s block:present_cyan
give @s block:present_light_blue
give @s block:present_blue
give @s block:present_purple
give @s block:present_magenta
give @s block:present_pink
gamerule sendcommandfeedback true