gamerule sendcommandfeedback false
give @s block:smooth_plastic_white
give @s block:smooth_plastic_light_gray
give @s block:smooth_plastic_gray
give @s block:smooth_plastic_black
give @s block:smooth_plastic_brown
give @s block:smooth_plastic_red
give @s block:smooth_plastic_orange
give @s block:smooth_plastic_yellow
give @s block:smooth_plastic_lime
give @s block:smooth_plastic_green
give @s block:smooth_plastic_cyan
give @s block:smooth_plastic_light_blue
give @s block:smooth_plastic_blue
give @s block:smooth_plastic_purple
give @s block:smooth_plastic_magenta
give @s block:smooth_plastic_pink
gamerule sendcommandfeedback true