gamerule sendcommandfeedback false
give @s block:table_white
give @s block:table_light_gray
give @s block:table_gray
give @s block:table_black
give @s block:table_brown
give @s block:table_red
give @s block:table_orange
give @s block:table_yellow
give @s block:table_lime
give @s block:table_green
give @s block:table_cyan
give @s block:table_light_blue
give @s block:table_blue
give @s block:table_purple
give @s block:table_magenta
give @s block:table_pink
gamerule sendcommandfeedback true