gamerule sendcommandfeedback false
give @s block:wall_clock_white
give @s block:wall_clock_light_gray
give @s block:wall_clock_gray
give @s block:wall_clock_black
give @s block:wall_clock_brown
give @s block:wall_clock_red
give @s block:wall_clock_orange
give @s block:wall_clock_yellow
give @s block:wall_clock_lime
give @s block:wall_clock_green
give @s block:wall_clock_cyan
give @s block:wall_clock_light_blue
give @s block:wall_clock_blue
give @s block:wall_clock_purple
give @s block:wall_clock_magenta
give @s block:wall_clock_pink
gamerule sendcommandfeedback true