gamerule sendcommandfeedback false
give @s block:oak_cabinet
give @s block:spruce_cabinet
give @s block:birch_cabinet
give @s block:jungle_cabinet
give @s block:acacia_cabinet
give @s block:dark_oak_cabinet
give @s block:crimson_cabinet
give @s block:warped_cabinet
gamerule sendcommandfeedback true